services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1123860023stocken
      POSTGRES_DB: stocken
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:1123860023stocken@db:5432/stocken
      - NODE_ENV=development
      - PORT=4000
      - SECRET_KEY=1123860023Stocken
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: