# Usamos una imagen oficial de Node.js
FROM node:18

# Creamos una carpeta en el contenedor
WORKDIR /app

# Copiamos el package.json y package-lock.json
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto de los archivos
COPY . .

# Exponemos el puerto 4000
EXPOSE 4000

# Comando para correr el servidor
CMD ["npm", "start"]